### PR TITLE
Update app.json

### PR DESCRIPTION
**Pull request by infotechbro**

### CODE REVIEW

**Comment by infotechbro** [comment]
Not for legendx

**Comment by LEGENDXOP** [comment]
Waah kanger aagyaa

**Comment by infotechbro** [comment]
Tu hena kanger

**Comment by infotechbro** [comment]
😑

**Comment by LEGENDXOP** [comment]
> Tu hena kanger

Tu he kanger mera session hack bot ka repo dhoondraha he kang krne ke liye

**Pull request closed without merging**
